Update create-release-branch-v1.yml

diff --git a/.github/workflows/create-release-branch-v1.yml b/.github/workflows/create-release-branch-v1.yml
--- a/.github/workflows/create-release-branch-v1.yml
+++ b/.github/workflows/create-release-branch-v1.yml
@@ -166,7 +166,7 @@ jobs:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           # GH_TOKEN: ${{ secrets.ORG_ADMIN_PAT }}
         run: |
-          set -ex # Exit immediately if a command exits with a non-zero status.
+          set -e # Exit immediately if a command exits with a non-zero status.
           source ./workflow_functions.sh
  
           if [ "$DRY_RUN" = "true" ]; then
@@ -265,7 +265,7 @@ jobs:
           # Use the token generated from the GitHub App
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          set -ex # Exit immediately if a command exits with a non-zero status.
+          set -e # Exit immediately if a command exits with a non-zero status.
           source ./workflow_functions.sh
  
           echo "--- Checking REPOSITORY: openstack-k8s-operators-ci ---"
