Update create-release-branch-v1.yml

diff --git a/.github/workflows/create-release-branch-v1.yml b/.github/workflows/create-release-branch-v1.yml
--- a/.github/workflows/create-release-branch-v1.yml
+++ b/.github/workflows/create-release-branch-v1.yml
@@ -270,7 +270,7 @@ jobs:
           # Use the token generated from the GitHub App
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          set -e # Exit immediately if a command exits with a non-zero status.
+          set -ex # Exit immediately if a command exits with a non-zero status.
           source ./workflow_functions.sh
           
           echo "--- Checking REPOSITORY: openstack-k8s-operators-ci ---"
@@ -309,7 +309,7 @@ jobs:
             fi
 
             echo "Found 'Create the catalog index' step at index: $index"
-            CURRENT_VERSION=get_yaml_value "${WORKFLOW_FILE}" ".steps[$index].env.MAIN_VERSION"
+            CURRENT_VERSION=get_yaml_value "${WORKFLOW_FILE}" ".jobs.build-catalog.steps[$index].env.MAIN_VERSION"
             FULL_NEW_VERSION="${NEW_VERSION}.0"
             # 3. Use the index to update the 'image' field in place (-i)
             update_yaml_value "${WORKFLOW_FILE}" ".jobs.build-catalog.steps[$index].env.MAIN_VERSION" "${FULL_NEW_VERSION}"
